### ISSUE TITLE
Bio text is cut off for some viewports

### ISSUE THREAD

**Issue by arlesondak** [stevedpedersen/spotify-infosuite#1]
For larger monitor sizes, the top and bottom of the Bio text is getting cut off.

Repro Steps:
1. Run app on large monitor (bigger than 1440x900 MacBook Pro size)

Observed Results: Notice parts (mainly top and bottom) of Bio text is cutoff
Expected Results: No text is cutoff, and text is formatted to fit inside frame.

![screen shot 2017-11-09 at 9 24 38 am](https://user-images.githubusercontent.com/7718144/32624890-7f86118c-c53f-11e7-8107-37aca13f23f2.png)

**Comment by stevedpedersen** [comment]
Is this fixed now that we have scrollbars?
